//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M151_Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortgage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mortgage()
        {
            this.MortgageCustomerAssignment = new HashSet<MortgageCustomerAssignment>();
        }
    
        public int id { get; set; }
        public string morgageName { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> fk_risk { get; set; }
    
        public virtual Risk Risk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MortgageCustomerAssignment> MortgageCustomerAssignment { get; set; }
    }
}
