//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M151_Projekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MortgageCustomerAssignment
    {
        public int id { get; set; }
        public Nullable<int> fk_customer { get; set; }
        public Nullable<int> fk_mortgage { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Mortgage Mortgage { get; set; }
    }
}
